name = "Commas"
uuid = "acc5c61a-a0db-11e8-1c12-8dfca70fca33"
authors = ["Kevin Atteson <kevin@atteson.com>"]
version = "0.1.0"

[deps]
BusinessDays = "4f18b42c-503e-5345-9536-bb0f25fc7038"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
ZippedArrays = "8051824b-fc5e-4603-89c4-0e6ea551cb88"
